### PR TITLE
Add usage to readme

### PR DESCRIPTION
**Pull request by ascandella**
This explains how to configure and use the plugin.

Preview here: https://github.com/uber/phabricator-jenkins-plugin/tree/update-readme

@zheller @Ignas

### CODE REVIEW

**Comment by rodrigc** [comment]
@sectioneight , this is really cool stuff.
I am a developer with the FreeBSD project, and set up Jenkins:  https://jenkins.freebsd.org
The FreeBSD project also uses Phabricator : https://reviews.freebsd.org . @grimreaper (Eitan Adler) works on that.

I don't know if you are in the SF Bay Area, but I am.  Would love to have a chat with you some time
for ideas as to how to use this plugin in a Jenkins + Phabricator environment.

**Comment by sectioneight** [comment]
Cool! I work in SF for uber but am in Seattle for the next two weeks
helping build out our Seattle team. Let's find some time when I'm back to
chat, since I'm really curious how well this is working for others.

Alternatively we could set up a video call if you're in the middle of an
implementation.

**Comment by rodrigc** [comment]
@sectioneight ,  enjoy your time in Seattle.  @grimreaper (Eitan Adler) is in SF and
I am in SJ.  When you get back maybe we can have an informal chat and BEvERage of your
choice.  In FreeBSD we aren't integrating Jenkins and Phabricator yet, but having an informal chat with you about your experience would be helpful.

**Comment by sectioneight** [comment]
Sounds good. I'll be back in SF 6/24. Why don't we move this to email -- I'm ai@uber.com

**Pull request merged**
