### PR TITLE
Add support for `arc lint --output=json` result

### LINKED ISSUE #255: Reporting Lint result fails
Lint results are not reported to phabricator. 

The lint results are successfully written to a file and also read by the plugin.

Content of the Lint file:
```
{"Makefile":[{"line":9,"char":1,"code":"TXT2","severity":"error","name":"Tab Literal","description":"Configure your editor to use spaces for indentation.","original":"\t","replacement":null,"granularity":1,"locations":[],"bypassChangedLineFiltering":null,"context":"ARGUMENTS=$(filter-out $@,$(MAKECMDGOALS))\n\nhelp: ## Show this help\n\t$(info Available targets)\n\t@awk '\/^[a-zA-Z\\-\\_0-9]+:\/ { \\\n\t\tnb = sub( \/^## \/, \"\", helpMsg ); \\\n\t\tif(nb == 0) { \\"}]}
```

Jenkins logs:
```
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:process-build-result] No unit results available.
[phabricator:process-build-result] No coverage provider available.
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-XXXX
[phabricator:process-build-result] Publishing lint results for 1 violations
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-XXXX, success: false
[phabricator:send-harbormaster-result] Error from Harbormaster: Missing required parameters: name, code, severity, path
[phabricator:send-harbormaster-result] Unable to post to Harbormaster
[phabricator:send-harbormaster-result] Error sending Harbormaster unit results, trying again without unit data (you may have an old Phabricator?).
[phabricator:file-fetcher] no file configured
```
So the plugin has found one violation in the file which is correct. 

I've just debugged what phabricator receives and it is an empty lint result.
The POST sent to phabricator contains this body
```
{"params":"{\"type\":\"fail\",\"buildTargetPHID\":\"PHID-HMBT-XXX\",\"lint\":[{}],\"__conduit__\":{\"token\":\"api-XXX\"}}"}
```
So the lint result is getting lost somewhere in the plugin between https://github.com/uber/phabricator-jenkins-plugin/blob/93043b1ab74406c537490d96e1ffa4290585ceb8/src/main/java/com/uber/jenkins/phabricator/BuildResultProcessor.java#L229
and 
https://github.com/uber/phabricator-jenkins-plugin/blob/93043b1ab74406c537490d96e1ffa4290585ceb8/src/main/java/com/uber/jenkins/phabricator/tasks/SendHarbormasterResultTask.java#L57

### PR DESCRIPTION
**Pull request by sascha-egerer**
Resolves #255

### CODE REVIEW

**Comment by sascha-egerer** [comment]
I really don't know why there are different JSON formats. If i just use the offical arcanist with `arc lint --output=json` i get a result like
```
{"path\/to\/file.xx": [{"line": 12 ...},{"line": 13 ...}]}
```

**Comment by kageiit** [comment]
Can you fix the tests?

**Comment by kageiit** [comment]
Ping. This will be closed in 2 more weeks due to inactivity

**Comment by sascha-egerer** [comment]
@kageiit Does it make sense to fix the testes? I mean this will be a breaking change. Should there be some kind of feature switch to define which format to use? Or how do you think about it?

**Pull request closed without merging**
