### PR TITLE
Abort existing builds when a new build referencing same diff is scheduled

### PR DESCRIPTION
**Pull request by kageiit**
- Checks for a parameter `ABORT_ON_REVISION_ID`
- Aborts other currently running builds with the same revision
- Aborted jobs skip notifying phabricator

### CODE REVIEW

**Comment by kageiit** [comment]
Tested via `mvn hpi:run`

screen shot 2016-08-11 at 1 45 43 pm

**Comment by sectioneight** [comment]
Tests?

**Comment by kageiit** [comment]
> Tests?

I tried to add some, but that needs multiple jobs to be building in parallel to be able to verify. Can you suggest ways to accomplish that in the current test code?

**Comment by sectioneight** [comment]
Will check when I'm back from vacation. Perhaps there's some way to unit
rather than integration test it? If not, not the end of the world.

**Comment by ChaitanyaPramod** [comment]
Closes #144

**Comment by sectioneight** [comment]
Can you add some docs (maybe under the new "advanced" doc page) about how/why/when to use this feature? Also, changelog.

**Comment by ChaitanyaPramod** [comment]
I've studied the change and see that it aborts only those builds of the same revision which have already started. It doesn't affect the pending build tasks on CI (where we are losing much more time), so this PR doesn't close #144.

I'll take a stab at fixing #144 in the coming weeks.

Good work. Appreciate any effort to save CI time.

**Pull request merged**
