### PR TITLE
Add option to create branch when applying diff

### PR DESCRIPTION
**Pull request by cellscape**

### CODE REVIEW

**Comment by sectioneight** [comment]
Can you please add your reasoning for this change? As I commented on the JIRA ticket, having this option will cause patch corruption in git if you test the same diff more than 9 times. 

Is this just a workaround for other SCMs? If so, we need to have SCM configurations that choose the right options instead of flagging each sub component and expecting users to figure out the right combination.

**Comment by cellscape** [comment]
Sorry, I was not aware of any problems with that and didn't think of describing the issue, should have searched better. Could you please share the link to discussion?

I need it for git, not other SCM. My build wants to know current branch name to include that into debian package name, this way we can have debs built from several branches sitting happily in the same repo (i.e. package-master, package-feature-branch, package-arcpatch-D1, etc) and arc patch generates nice branch name. 

I can make workaround in my build system but thought that arc already can do that for me and why not try to do this in plugin.

I didn't yet try to apply the same patch >9 times and didn't see the corruption. However even if it corrupts then I think it's better to find the root cause of corruption and fix it but provide such an option.

**Comment by sectioneight** [comment]
Here is the corruption I'm describing:

```
for i in {1..10} ; do ; arc patch D256896 ; git checkout master ; done
...
Your branch is up-to-date with 'origin/master'.
Branch name arcpatch-D256896 already exists; trying a new name.
Branch name arcpatch-D256896_1 already exists; trying a new name.
Branch name arcpatch-D256896_2 already exists; trying a new name.
Branch name arcpatch-D256896_3 already exists; trying a new name.
Exception
Arc was unable to automagically make a name for this patch. Please clean up your working copy and try again.
(Run with `--trace` for a full exception trace.)
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```

The first four times succeed, but the fifth time fails and you need to manually delete branches before arc can patch again.

So if you're willing to live with that limitation, I'm OK merging this, but you have to be careful.

Let me know how you'd like to proceed.

**Comment by cellscape** [comment]
This is clearly a problem with arc and I don't see why this plugin should hide it. Once I encounter such situation on my side, I'll investigate it and report to upstream. Meanwhile I would like to have this pull request merged in if it's ok with you. Thanks!

**Comment by sectioneight** [comment]
I'm fairly certain they're aware of it and it's intentional. We're not
really using arc patch as it was intended to be used (by humans, who could
clean up the branches)

So I'm fine merging, but don't expect that the behavior of arcanist is
going to change, so make sure that if you use the option you have some
cleanup phase that can prune these branches for you.

**Pull request merged**
