### PR TITLE
Add Subversion support

### PR DESCRIPTION
**Pull request by lwhsu**

### CODE REVIEW

**Comment by lwhsu** [comment]
I've signed the CLA, but for some unknown reason the check status is not updated.

**Comment by sectioneight** [comment]
This is awesome! Out of curiosity, why the workdir change as well?

**Comment by sectioneight** [comment]
Also, can we add a simple test that sets the scm type to "svn" and does some simple assertions?

**Comment by lwhsu** [comment]
Thanks for the review, @sectioneight 

In some cases, we want to specify the scm check out path, which is "check out to a sub-directory" in git and "local module directory" in svn.  Add workdir config to let arc find the right working copy path.

I will add some tests later.

**Comment by lwhsu** [comment]
One of the travis-ci jobs failed due to underlaying executor hang, however this branch is fine in my travis-ci account: https://travis-ci.org/lwhsu/phabricator-jenkins-plugin/builds/221607816

**Comment by lwhsu** [comment]
Thanks! Is it worth to have a new release? 😃

**Comment by sectioneight** [comment]
Unfortunately releases are blocked on https://github.com/uber/phabricator-jenkins-plugin/issues/189 due to some changes with Jenkins 2.0 and some of our dependencies. You can deploy it yourself by running `mvn hpi:package` and uploading the .hpi to your jenkins master (what we do at Uber to work around #189).

**Pull request merged**
