### PR TITLE
Call conduit with JSON params

### PR DESCRIPTION
**Pull request by sectioneight**
This will allow us to pass more complex objects, which is a requirement for
passing lint/unit results.

### CODE REVIEW

**Comment by sectioneight** [comment]
@jjx

**Comment by sectioneight** [comment]
Tested manually on my local Phabricator instance. @jjx does Java have something like VCR where I can record requests against a "real" Phabricator API and check in the responses as flat files for future replaying / "integration" tests?

**Comment by jjx** [comment]
Maybe http://freeside.co/betamax?

**Comment by jjx** [comment]
:dancers:

**Comment by sectioneight** [comment]
Cool, I will look at that in a future diff

**Pull request merged**
