### PR TITLE
Add windows detection when executing `arc`

### PR DESCRIPTION
**Pull request by colin-harms**
This is in relation to https://github.com/uber/phabricator-jenkins-plugin/issues/244
If the ApplyPatchTask is being instantiated as part of a build, it will check the JVM's "os.name" property to see if it's Windows. The "startsWith Windows" logic was lifted from common-lang's SystemUtils.IS_WINDOWS

I've been trying to get a proper unit test going for this, but because Computer.currentComputer() checks to see if the current thread is a Hudson Executor, it will fail in normal unit tests (as in ApplyPatchTaskTest)

If it runs as  a build in the PhabricatorBuildWrapperTest class, it will actually check the values of "os.name", but I don't want to override it as part of the test, since it sets it globally across the jvm that is running the test.

I'm open to suggestions to create a lightweight test for this. I'm not very familiar with Jenkins plugin development, but I did run into that "arc" vs "arc.bat" problem, and this change solved it.

### CODE REVIEW

**Comment by kageiit** [comment]
@colin-harms can you please sign the CLA?

**Comment by withinfocus** [comment]
@colin-harms can you respond to the above? We'd love to get this included for our own purposes as we're experiencing the same issue with multi-platform builds.

**Comment by colin-harms** [comment]
@withinfocus I signed it a while ago, I'm not sure why it's not recognising that I haven't.

**Comment by kageiit** [comment]
I closed and re-opened the PR for the checks to trigger again

**Comment by withinfocus** [comment]
@colin-harms Maybe go to https://cla-assistant.io/uber/phabricator-jenkins-plugin?pullRequest=270 again and see if it sticks?

**Comment by colin-harms** [comment]
I've tried chrome, chrome incognito, firefox ( which I never use ), signing out of CLA and back in.  The signing page always switches from "Please sign ... " to "You have signed ... ".
Not sure what I can do to push this forward

**Comment by withinfocus** [comment]
@kageiit can this be manually resolved then?

**Comment by withinfocus** [comment]
Bump on this one. Would love for it to come through in the next plugin release. Can someone at Uber commandeer this and merge it themselves?

**Comment by kageiit** [comment]
@briankhsieh Any idea why the CLA is not being recognized?

**Comment by kageiit** [comment]
@withinfocus can you please resolve the conflicts?

**Comment by briankhsieh** [comment]
Hi can you trysign the CLA with username @ch4rms ?

**Comment by ch4rms** [comment]
It finally worked!!
IIRC, the last time I tried the CLA form, it wasn't prompting me for my details or showing me the check box (it's been a while)

**Comment by kageiit** [comment]
@ch4rms can you please resolve the merge conflicts?

**Comment by ch4rms** [comment]
Thanks @kageiit I was just fixing it up when I got the email notification :)

**Pull request merged**
