### PR TITLE
Reset git to provided commit SHA1 for non-differential builds

### LINKED ISSUE #135: Plugin doesn't use the commit in phid for non-differential builds

### PR DESCRIPTION
**Pull request by ChaitanyaPramod**
closes #135

### CODE REVIEW

**Comment by sectioneight** [comment]
Nice. I like this approach. I'd like to add some unit tests before we
merge. I'm happy to do that if you're comfortable with me grabbing your
branch.

**Comment by ChaitanyaPramod** [comment]
@sectioneight It's all yours

**Comment by sectioneight** [comment]
Actually, on second thought, I think we should not include this logic and just document how to check out the correct SHA for you SCM. I'm slowly trying to make this more SCM agnostic (to support mercurial and I guess SVN) and we should instead have people configure Jenkins to pull the correct commit. You will still pass the `COMMIT_ID` field (or whatever you want to call it), but do this with that parameter:

image

(repo URL is redacted)

What do you think?

**Comment by ChaitanyaPramod** [comment]
I based this change on `ApplyPatchTask` which is quite coupled to `git`.

If we want to make the plugin SCM agnostic, then yes, what you suggested is the right approach.

**Comment by sectioneight** [comment]
Yea, the way the upstream phabricator guys are moving is to make the apply patch stuff obsolete with staging areas. It's fewer moving parts (and no need to install arcanist on your Jenkins nodes). Which is a win win.

**Pull request closed without merging**
