### PR TITLE
Add unit test for CodeCoverageMetrics

### PR DESCRIPTION
**Pull request by sectioneight**
Really just trolling for coverage at this point, but I noticed a large
amount of uncovered code in here which was easy to knock out.

### CODE REVIEW

**Comment by sectioneight** [comment]
@jjx

**Comment by sectioneight** [comment]
Looks like coveralls is having some queueing issues: http://status.coveralls.io/

**Comment by sectioneight** [comment]
screen shot 2015-07-22 at 8 33 26 pm

**Comment by jjx** [comment]
lgtm

**Pull request merged**
