### PR TITLE
Send build url to Harbormaster as soon as build starts

### LINKED ISSUE #94: Deprecate "build started" messages
Now that Harbormaster supports artifacts (e.g. build links), we can reduce clutter and remove this option.

TODO: Add the build artifact in the Wrapper step as well.

### LINKED ISSUE #133: Adding URL artefact to build before CI finishes build
Context: Our builds are sometimes long (order of minutes). It'll be useful to see the Jenkins build job link in Phabricator as soon the build is started (as opposed to the link being added at the end of the build job).

Do you guys think if Phabricator allows this with their Harbormaster APIs?

### PR DESCRIPTION
**Pull request by ChaitanyaPramod**
Closes #133
Closes #94

### CODE REVIEW

**Comment by sectioneight** [comment]
Awesome. You want to fix the tests, or should I?

**Comment by ChaitanyaPramod** [comment]
Fixed tests, ready for review

**Comment by sectioneight** [comment]
Almost there. This now assumes you're using both the build wrapper and the notifier. However, some people use just the notifier, and instead of applying with arc patch, they configure a staging area. So this is the right approach, but we need to still send the artifact URI in the notifier (aka build result processor). The only thing I haven't tested is whether if you send two artifacts with the same name to the same build PHID how that shows up in the differential UI. Hopefully it just displays one link.

**Comment by ChaitanyaPramod** [comment]
That's fair. I've reverted changes to `BuildResultProcessor` for those cases.

**Comment by sectioneight** [comment]
Ok, I just tested what happens when you try to send two artifacts with the same key:

```
{"error":"ERR-CONDUIT-CORE","errorMessage":"ERR-CONDUIT-CORE: #1062: Duplicate entry 'uri-PwLy5JFwgQcn' for key 'key_artifact'","response":null}
```

It looks like we'll pass with an INFO message in the `BuildResultProcessor`

```java
            logger.info("harbormaster", "Sending Harbormaster BUILD_URL via PHID: " + phid);
            Task.Result sendUriResult = new SendHarbormasterUriTask(logger, diffClient, phid, buildUrl).run();

            if (sendUriResult != Task.Result.SUCCESS) {
                logger.info(LOGGING_TAG, "Unable to send BUILD_URL to Harbormaster");
            }
```

I think this is acceptable behavior. I'll probably tweak the message a little bit when this fails to say that this is normal, and to be expected if you're running the BuildWrapper (e.g. the `arc patch`) stage.

**Pull request merged**
