### PR TITLE
Updated HttpClient to a version that's not removed

### PR DESCRIPTION
**Pull request by betterphp**
Fixes issue #356

### CODE REVIEW

**Comment by jonathanbaker7** [comment]
This PR has been escalated into the Uber OSPO, and we will try to put together a team to review it so that you can go back to operational status.  I can't tell you when, yet, because it's just come in today, but we will try to get updated soon.

**Comment by betterphp** [comment]
Cool thanks :)

**Review by jonathanbaker7 — APPROVED** [review]
I'm not an expert with Phabricator, but I am a Java developer and have experience with Jenkins.  I don't see any problems with these changes, so I'm going to approve them to move this back into support.

**Comment by betterphp** [comment]
Great thanks, we've been running a version of the plugin with these changes for about 3 weeks and haven't had any problems with it.

Would it be possible to do a 2.1.6 release to get this in to the jenkins plugin repo?

**Comment by TheWrongGuy** [comment]
Just wanted to report that your fix works perfectly!

**Pull request merged**
